### PR TITLE
project: upgrade lombok to v1.18.20

### PR DESCRIPTION
**Pull request by Infinitay**
Had issues myself when on version 1.18.16 of lombok and upgrading to 1.18.20 solved my issues.

JDK 11 by the way.

### CODE REVIEW

**Comment by Ganom** [comment]
> Had issues myself when on version 1.18.16 of lombok and upgrading to 1.18.20 solved my issues.
> 
> JDK 11 by the way.

Interesting, what issue in particular did you have?

**Comment by Infinitay** [comment]
Going off by my Google search history, it was something along the lines of,
> class lombok.javac.apt.LombokProcessor cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module

Again, what seemed to fix it for me was upgrading it to 1.18.20. Though I was under the assumption that 1.18.16 already supported JDK 11. Not exactly sure what the issue was but it resolved all my issues after upgrading. Came to doing so as a result of a S.O. suggestion.

**Comment by Ganom** [comment]
> Going off by my Google search history, it was something along the lines of

Gotcha, any reason for not going with latest version of lombok?

**Comment by Infinitay** [comment]
> > Going off by my Google search history, it was something along the lines of
> 
> Gotcha, any reason for not going with latest version of lombok?

No reason in particular. I just tried the solution that was listed and it worked, so I didn't bother doing anything else. If you would like I could change it.

**Comment by Ganom** [comment]
> No reason in particular. I just tried the solution that was listed and it worked, so I didn't bother doing anything else. If you would like I could change it.

No worries, I'll update it to the latest version and other deps and push a version update as well for them. I appreciate the PRs!

**Review by Ganom — APPROVED** [review]

**Pull request merged**
